export const categroies = [
  { key: "nextjs", value: 'Next Js' },
  { key: "reactjs", value: "React Js" },
  { key: "javascript", value: "Javascript" },
  { key: "html", value: "HTML" },
  { key: "css", value: "CSS" },
  { key: "aws", value: "AWS" },
  { key: "cloud", value: "Cloud" },
  { key: "cloudarchitecture", value: "Cloud Architecture" },
  { key: "vim", value: "Vim" },
  { key: "azure", value: "Azure" },
  { key: "nodejs", value: "Node JS" },
  { key: "expressjs", value: "Express Js" },
  { key: "mongoodb", value: "MongooDB" },
  { key: "mongoose", value: "Mongoose" },
  { key: "aggregation", value: "Aggregation" },
  { key: "jesonwebtoken", value: "Jesonwebtoken" },
  { key: "jwt", value: "JWT" },
  { key: "firebaseauthentication", value: "Firebase Authentication" },
  { key: "firebase", value: "Firebase" },
];